# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_john F69C50ED361996D5C52ECAB9BBBF15A1AB9C1345
  - &laptop_pluto age13gdjk0dln0agxt6hj9f2ufjtw97l57s52xa4m6u92fntxvlj65dq9qegna
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *admin_john
      age:
      - *laptop_pluto
