# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6e9a0dc3-f1a1-4e33-9cf9-06329b7c6941";
      fsType = "btrfs";
      options = [ "subvol=@nixos" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/c7f90ee9-be7a-4c12-89f1-d0c3f093c0b0";

#  fileSystems."/home" =
#    { device = "/dev/disk/by-uuid/6e9a0dc3-f1a1-4e33-9cf9-06329b7c6941";
#      fsType = "btrfs";
#      options = [ "subvol=@home-nixos" ];
#    };
#
#  fileSystems."/var/lib/libvirt" =
#    { device = "/dev/disk/by-uuid/6e9a0dc3-f1a1-4e33-9cf9-06329b7c6941";
#      fsType = "btrfs";
#      options = [ "subvol=@libvirt" ];
#    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BD99-62EC";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

#  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.video.hidpi.enable = true;
  hardware.opengl = {
    enable = true;
    driSupport = true;
    extraPackages = with pkgs; [
      intel-media-driver
      vaapiVdpau
      libvdpau-va-gl
    ];
  };
}
